apiVersion:  apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 7
  #select pod
  selector:
    matchLabels:
      app: web
  #template of pod with label pod
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80

